"""sprint6_fee_payments

Revision ID: 02fb95e1f181
Revises: aecaeb364edd
Create Date: 2026-06-21 18:12:50.414482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fb95e1f181'
down_revision = 'aecaeb364edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_record_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('receipt_no', sa.String(length=20), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'bank_transfer', 'cheque', 'online')", name='ck_fee_payments_payment_method'),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fee_record_id'], ['fee_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_payments_collected_by'), ['collected_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_payments_fee_record_id'), ['fee_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_payments_receipt_no'), ['receipt_no'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_payments_receipt_no'))
        batch_op.drop_index(batch_op.f('ix_fee_payments_fee_record_id'))
        batch_op.drop_index(batch_op.f('ix_fee_payments_collected_by'))

    op.drop_table('fee_payments')
    # ### end Alembic commands ###
