"""sprint4_attendance_notifications

Revision ID: 0a44164dd313
Revises: bd56c0cea795
Create Date: 2026-06-12 15:52:30.638489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a44164dd313'
down_revision = 'bd56c0cea795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'leave', 'holiday', name='attendance_status'), nullable=False),
    sa.Column('marked_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name='fk_attendance_marked_by'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='fk_attendance_section_id'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_attendance_student_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'section_id', 'date', name='uq_attendance_student_section_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('student_sections', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_student_sections_section_id_v2', 'sections', ['section_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_sections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_sections_section_id_v2', type_='foreignkey')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_section_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_date'))

    op.drop_table('attendance')
    # ### end Alembic commands ###
