"""sprint6_fee_records

Revision ID: aecaeb364edd
Revises: fc0f55f9d6e2
Create Date: 2026-06-21 15:26:38.435816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecaeb364edd'
down_revision = 'fc0f55f9d6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending','paid','partial','waived')", name='ck_fee_records_status'),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'fee_structure_id', name='uq_fee_records_student_fee_structure')
    )
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_records_fee_structure_id'), ['fee_structure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_records_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_fee_records_fee_structure_id'))

    op.drop_table('fee_records')
    # ### end Alembic commands ###
