"""sprint6_discounts

Revision ID: b7407516626b
Revises: 02fb95e1f181
Create Date: 2026-06-21 18:47:35.465377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7407516626b'
down_revision = '02fb95e1f181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_record_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("discount_type IN ('scholarship', 'sibling', 'staff', 'custom')", name='ck_discounts_discount_type'),
    sa.CheckConstraint('amount > 0', name='ck_discounts_amount_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fee_record_id'], ['fee_records.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discounts_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_discounts_fee_record_id'), ['fee_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discounts_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discounts_student_id'))
        batch_op.drop_index(batch_op.f('ix_discounts_fee_record_id'))
        batch_op.drop_index(batch_op.f('ix_discounts_approved_by'))

    op.drop_table('discounts')
    # ### end Alembic commands ###
