"""sprint5_exam_definitions

Revision ID: d2d4edc832d7
Revises: 0a44164dd313
Create Date: 2026-06-13 12:42:16.419494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d4edc832d7'
down_revision = '0a44164dd313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('exam_type', sa.String(length=20), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('conducted_date', sa.Date(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("exam_type IN ('midterm', 'final', 'unit_test', 'practical')", name='ck_exam_exam_type'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_section_id'), ['section_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_section_id'))
        batch_op.drop_index(batch_op.f('ix_exams_academic_year_id'))

    op.drop_table('exams')
    # ### end Alembic commands ###
